project:
  type: book
  output-dir: _site

book:
  title: "Moloch"
  subtitle: "A Minimalist, Feature-Rich Beamer Theme"
  description: |
    Moloch is a minimalist, feature-rich Beamer theme for LaTeX presentations
    with a clean design and extensive customization options.

  output-file: moloch
  open-graph:
    title: "Moloch - A Minimalist, Feature-Rich Beamer Theme"
    locale: en_US
    image: images/og.jpg
  twitter-card:
    image: images/og.jpg
  favicon: images/favicon.svg
  image: images/og.jpg
  author:
    - name: "Johan Larsson"
    - name: "Matthias Vogelgesang"
      note:
        "Matthias wrote the original version of this manual for the Metropolis
        theme."
  date: today

  repo-url: "https://github.com/jolars/moloch"
  site-url: "https://moloch.ink"
  repo-branch: main

  search: true

  page-footer:
    left: "Moloch v{{< meta version >}} | Copyright 2024-2025, Johan Larsson"
    right:
      - icon: github
        href: "https://github.com/jolars/moloch"
        aria-label: "Source for this webpage"
  chapters:
    - index.md
    - part: User Guide
      chapters:
        - getting-started.md
        - customization.md
        - commands.md
        - known-issues.md
        - license.md
  appendices:
    - part: Implementation
      chapters:
        - implementation/beamerthememoloch.md
        - implementation/beamerinnerthememoloch.md
        - implementation/beamerouterthememoloch.md
        - implementation/beamerfontthememoloch.md
        - implementation/beamercolorthememoloch.md
        - implementation/beamercolorthememoloch-tomorrow.md
        - implementation/beamercolorthememoloch-highcontrast.md

highlight-style: breeze

format:
  html:
    toc: true
    theme:
      light: flatly
      dark: darkly
    css: styles.css
    html-math-method: katex
    include-in-header:
      file: header.html
  pdf:
    documentclass: scrreprt
    classoption: toc=graduated
    toc: true
    number-sections: true
    colorlinks: true
    include-in-header:
      text: |
        \usepackage{xspace}
        \usepackage{parskip}
        \usepackage{doc}
        \usepackage{xcolor}
        \usepackage{makeidx}
        \makeindex
        \definecolor{JungleGreen}{RGB}{42,127,98}
        \newcommand{\DescribeOption}[4]{
          \begin{minipage}[t]{\textwidth}
            \texttt{#1}
            \textit{\textbf{\textcolor{JungleGreen}{#2}}}\dotfill\,#3\par
            \begingroup
            \vspace{0.5em}#4\par
            \endgroup
          \end{minipage}
        }
        \newcommand{\DescribeKey}[4]{
          \begin{minipage}[t]{\textwidth}
            \texttt{#1}
            \textit{\textbf{\textcolor{JungleGreen}{#2}}}%
            \ifx&#3&\else\dotfill\,default: #3\fi\par
            \begingroup
            \vspace{0.5em}#4\par
            \endgroup
          \end{minipage}
        }
    include-after-body:
      text: |
        \printindex

execute:
  freeze: auto

toc: true
date-format: "D MMMM YYYY"

filters:
  - filters/pre-render.lua
  - filters/describe-option.lua
  - filters/describe-key.lua
