project:
  type: book
  output-dir: _site

book:
  title: "Moloch"
  subtitle: "A Functional and Minimalist Beamer Theme"
  description: |
    Moloch is a functional and minimalist Beamer theme for LaTeX presentations.
    It tries to keep things simple while still providing a flexible
    and modern design.

  output-file: "moloch"
  open-graph:
    locale: en_US
  twitter-card: true
  favicon: images/favicon.svg
  cover-image: images/cover.jpg
  image: images/og.jpg

  author:
    - name: "Johan Larsson"
    - name: "Matthias Vogelgesang"
      note:
        "Matthias wrote the original version of this manual for the Metropolis
        theme."
  date: today

  repo-url: "https://github.com/jolars/moloch"
  site-url: "https://moloch.ink"
  repo-branch: main

  search: true

  page-footer:
    left: "Moloch v{{< meta version >}} | Copyright 2024-2025, Johan Larsson"
    right:
      - icon: github
        href: "https://github.com/jolars/moloch"
        aria-label: "Source for this webpage"
  chapters:
    - index.md
    - part: User Guide
      chapters:
        - getting-started.md
        - customization.md
        - commands.md
        - known-issues.md
        - license.md
    - part: "Implementation"
      chapters:
        - implementation/beamerthememoloch.md
        - implementation/beamerinnerthememoloch.md
        - implementation/beamerouterthememoloch.md
        - implementation/beamerfontthememoloch.md
        - implementation/beamercolorthememoloch.md
        - implementation/beamercolorthememoloch-tomorrow.md
        - implementation/beamercolorthememoloch-highcontrast.md

highlight-style: breeze

format:
  html:
    theme:
      light: flatly
      dark: darkly
    css: styles.css
    html-math-method: katex
    include-in-header:
      file: header.html
  pdf:
    documentclass: scrreprt
    classoption: DIV=10
    keep-tex: true
    toc: true
    number-sections: true
    colorlinks: true
    include-in-header:
      text: |
        \usepackage{xspace}
        \usepackage{parskip}
        \usepackage{doc}
        \usepackage{xcolor}
        \definecolor{JungleGreen}{RGB}{42,127,98}
        \newcommand{\DescribeOption}[4]{
          \begin{minipage}[t]{\textwidth}
            \texttt{#1}
            \textit{\textbf{\textcolor{JungleGreen}{#2}}}\dotfill\,#3\par
            \begingroup
            \vspace{0.5em}#4\par
            \endgroup
          \end{minipage}
        }

execute:
  freeze: auto

toc: true
date-format: "D MMMM YYYY"

filters:
  - _pre-render.lua
  - describe-option-filter.lua
